### ISSUE TITLE
Spell Error - Fix for kural 1000

### ISSUE THREAD

**Issue by tshrinivasan** [tk120404/thirukkural#3]
For kural 1000,

"Line1": "ண்பிலான் பெற்ற பெருஞ்செல்வம் நன்பால்",

Should be like

"Line1": "எண்பிலான் பெற்ற பெருஞ்செல்வம் நன்பால்",                                                                                                                

Please fix this.

Thanks.

**Comment by tk120404** [comment]
Got MR. Closing this issue
